### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by thewilloftheshadow** [ErikBoesen/mebots-example-javascript#3]
This code has lots of errors and missing parts and isn't working at all. I will be rewriting this example so that it actually works within the next couple of days

**Comment by thewilloftheshadow** [comment]
I gave up and just made my own that was much much much simpler than their spaghetti code
https://github.com/thewilloftheshadow/mebots-nodejs-example

**Comment by ErikBoesen** [comment]
@thewilloftheshadow Want to just copy your code and make a PR?

**Comment by ErikBoesen** [comment]
Yeah, I just built off GroupMe's official example, which is not very good. Thanks for your changes.

**Comment by thewilloftheshadow** [comment]
Done, see #4 
No problem! I'm happy to help :)
